- type: job
  id: TownShopkeeper
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-townshopkeeper
  description: job-description-townshopkeeper
  playTimeTracker: TownShopkeeper
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
      - Human
      - Ghoul
      #- Supermutant # Corvax-Change
    - !type:CharacterDepartmentTimeRequirement
      department: Townsfolk
      min: 7200 # 2 hours
    - !type:CharacterPlaytimeRequirement # Forge-Add
      tracker: TownShopkeeperHelper
      min: 14400 # 4 hours
  startingGear: TownShopkeeperGear
  icon: "JobIconTownShopKeeper" # Corvax-Change
  supervisors: job-supervisors-townsfolk
  alwaysUseSpawner: true # Corvax-Change
  access:
  - TownieShopkeeper
  - TownsPerson # Corvax-Change
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
          - Townsfolk
      - type: ProfessionalChef

- type: startingGear
  id: TownShopkeeperGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitMerchant
    back: N14ClothingBackpackHiking # Corvax-Change
    shoes: N14ClothingShoesBlack
    id: N14IDShopkeeperTown
    belt: N14WalletCash
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled  # N14TODO: Trader bag
  storage: # Corvax-Change
    back:
    - N14BoxPlasticFilledWastelander
    - N14NewYearsGift # Forge-Change

- type: playTimeTracker
  id: TownShopkeeper
