- type: job
  id: Followers
  setPreference: true # Forge-Change
  name: job-name-followers
  description: job-description-followers
  playTimeTracker: Followers
  startingGear: FollowersGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-followers
  alwaysUseSpawner: true # Corvax-Change
  accessGroups:
  - FollowersApocalypse
  # Forge-Change-Start
  special:
  - !type:AddComponentSpecial
    components:
      - type: NpcFactionMember
        factions:
          - Wastelander
      - type: CPRTraining
  # Forge-Change-End

- type: startingGear
  id: FollowersGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitFollowers
    back: N14ClothingBackpackWastelanderFilled # N14TODO: Doctors Bag
    shoes: N14ClothingBootsLeather # Forge-Change
    neck: ClothingNeckStethoscope # Forge-Change
    id: N14IDDoctorFollower
    outerClothing: N14ClothingOuterCoatFollowerLab # Forge-Change
    belt: N14ClothingBeltMedicalFilled
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack
  satchel: N14ClothingBackpackSatchelWastelanderFilled
  duffelbag: N14ClothingBackpackDuffelFilled  # N14TODO: Doctors Bag

- type: playTimeTracker
  id: Followers
