- type: job
  id: WastelandChaplain
  setPreference: true
  overrideConsoleVisibility: false
  canBeAntag: false
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: WastelandChaplain
  requirements:
    - !type:CharacterSpeciesRequirement # Forge-Add
      species:
      - Human
      - Ghoul
      #- Supermutant
    - !type:CharacterDepartmentTimeRequirement # Forge-Add
      department: Townsfolk
      min: 7200 # 2 hours
  startingGear: WastelandChaplainGear
  icon: "JobIconWastelandChaplain" # Forge-Change
  supervisors: job-supervisors-townsfolk
  alwaysUseSpawner: true # Corvax-Change
  access:
  - WastelandChaplain
  - TownsPerson # Forge-Change
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: NpcFactionMember # Forge-Add
      factions:
        - Townsfolk

- type: startingGear
  id: WastelandChaplainGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitFollowers
    back: N14ClothingBackpackTrekker # Forge-Change
    shoes: N14ClothingBootsBlack
    id: N14IDPassportWasteChaplain
  innerClothingSkirt: N14ClothingUniformJumpsuitFollowers
  satchel: N14ClothingBackpackSatchelChaplainFilled
  duffelbag: N14ClothingBackpackDuffelChaplainFilled
  storage: # Forge-Change
    back:
    - N14BoxPlasticFilledWastelander
    - Bible
    - N14NewYearsGift # Forge-Change

- type: playTimeTracker
  id: WastelandChaplain
